version: '3'
services:
  database:
    image: "postgres:latest"
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DBPASSWORD}
  nginx:
    image: zavanton/famount-nginx
    depends_on:
      - web
      - api
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  web:
    image: zavanton/famount-web
    build:
      context: ./web
      dockerfile: Dockerfile
  api:
    image: zavanton/famount-api
    env_file:
      - .env
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ./wait-for.sh database:5432 -- node build/app.js
volumes:
  dbdata:
networks:
  default:
    external:
      name: localdev
