version: '3'
services:
  database:
    image: "postgres:latest"
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres_password'
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - web
      - api
    restart: always
    ports:
      - "8080:80"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      #      - /usr/src/app/node_modules
      - ./api:/usr/src/app
    command: ./wait-for.sh database:5432 -- /usr/src/app/node_modules/.bin/nodemon src/app.ts
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      #      - /usr/src/app/node_modules
      - ./web:/usr/src/app
volumes:
  dbdata:
networks:
  default:
    external:
      name: localdev
