version: '3'
services:
  database:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: 'postgres_password'
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
#    volumes:
#      - /usr/src/app/node_modules
#      - ./api:/usr/src/app
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
#      - /usr/src/app/node_modules
      - ./web:/usr/src/app
networks:
  default:
    external:
      name: localdev
